# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://username.github.io/
baseurl: 
title: Thiago Ribeiro
author: Thiago Ribeiro
description: Personal website and blog about personal projects
avatar: profile.png
email: tor@ecomp.poli.br
github: biomadeira/sustain # username
twitter: username
linkedin: username
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: tolribeiro	
google_analytics: UA-61161310-1


# needed for travis-ci build
exclude: [vendor]
